/* Account secrets stay in memory. QR codes are generated by our own backend. */
(() => {
  'use strict';
  let csrf = '1', user = null, pending = false, registering = false;
  let resolveReady;
  window.accountReady = new Promise(resolve => { resolveReady = resolve; });
  const byId = id => document.getElementById(id);
  const gate = byId('accountGate'), app = document.querySelector('main');
  const dialog = byId('securityDialog');
  let recovery = [];

  async function request(action, body) {
    const res = await fetch('/api/account/' + action, {
      method: body === undefined ? 'GET' : 'POST', credentials: 'same-origin',
      headers: body === undefined ? {} : { 'Content-Type': 'application/json', 'x-reacher-csrf': csrf },
      ...(body === undefined ? {} : { body: JSON.stringify(body) })
    });
    const data = await res.json().catch(() => ({}));
    if (!res.ok) { const error = new Error(data.error || `Request failed (${res.status}).`); error.status = res.status; throw error; }
    if (data.csrf_token) csrf = data.csrf_token;
    return data;
  }
  window.accountFetch = async (path, options = {}) => {
    const headers = new Headers(options.headers || {});
    if (user && (options.method || 'GET').toUpperCase() !== 'GET') headers.set('x-reacher-csrf', csrf);
    const res = await fetch(path, { ...options, headers, credentials: 'same-origin' });
    if (res.status === 401 && user) location.reload();
    return res;
  };
  const message = (id, text) => { byId(id).textContent = text; };
  const announce = () => { try { localStorage.setItem('ec.auth-event', String(Date.now())); } catch (_) {} };
  window.addEventListener('storage', e => { if (e.key === 'ec.auth-event') location.reload(); });
  function signedIn(me) {
    user = me; window.accountUser = me;
    gate.hidden = true; app.hidden = false; byId('accountBar').hidden = false;
    message('accountName', me.username);
    resolveReady(me);
  }
  function loginView() {
    byId('loginFields').hidden = pending;
    byId('loginFactor').hidden = !pending;
    byId('authToggle').hidden = pending;
    byId('authBack').hidden = !pending;
    message('authTitle', pending ? 'Verify your sign-in' : registering ? 'Create your account' : 'Welcome back');
    message('authSubmit', pending ? 'Verify and sign in' : registering ? 'Create account' : 'Sign in');
    message('authToggle', registering ? 'Already have an account? Sign in' : 'New here? Create an account');
    byId('authUsername').required = !pending; byId('authPassword').required = !pending;
    byId('authCode').required = pending;
    byId('authPassword').minLength = registering ? 12 : 1;
    byId('authPassword').autocomplete = registering ? 'new-password' : 'current-password';
    byId('passwordHint').hidden = !registering;
  }
  byId('authToggle').addEventListener('click', () => { registering = !registering; message('authError', ''); loginView(); });
  byId('authBack').addEventListener('click', async () => {
    try { await request('logout', {}); } catch (_) {}
    pending = false; csrf = '1'; byId('authCode').value = ''; loginView();
  });
  byId('authForm').addEventListener('submit', async event => {
    event.preventDefault(); const button = byId('authSubmit'); button.disabled = true; message('authError', '');
    try {
      const data = await request(pending ? 'verify' : registering ? 'register' : 'login', pending
        ? { code: byId('authCode').value.trim() }
        : { username: byId('authUsername').value.trim(), password: byId('authPassword').value });
      byId('authPassword').value = ''; byId('authCode').value = '';
      if (data.mfa_required) { pending = true; loginView(); byId('authCode').focus(); }
      else { announce(); signedIn(await request('me')); }
    } catch (error) { message('authError', error.message); }
    finally { button.disabled = false; }
  });
  byId('signOut').addEventListener('click', async () => {
    try { await request('logout', {}); announce(); location.reload(); }
    catch (error) { message('accountError', error.message); }
  });

  function clearSensitive() {
    for (const form of dialog.querySelectorAll('form')) form.reset();
    byId('enrollment').hidden = true; byId('totpQr').removeAttribute('src');
    message('totpKey', ''); message('recoveryList', ''); recovery = [];
    byId('recoveryPanel').hidden = true;
  }
  dialog.addEventListener('close', clearSensitive);
  byId('securityClose').addEventListener('click', () => dialog.close());
  async function refreshSecurity() {
    user = await request('me'); window.accountUser = user;
    message('securityName', user.username);
    message('twoFactorStatus', user.two_factor_enabled ? 'Two-factor authentication is on' : 'Two-factor authentication is off');
    message('recoveryCount', user.two_factor_enabled ? `${user.recovery_codes_remaining} recovery codes remaining` : 'Add an authenticator app for extra sign-in protection.');
    byId('setupForm').hidden = user.two_factor_enabled;
    byId('manageTwoFactor').hidden = !user.two_factor_enabled;
    for (const field of dialog.querySelectorAll('[data-factor]')) {
      field.hidden = !user.two_factor_enabled;
      field.querySelector('input').required = user.two_factor_enabled;
    }
  }
  byId('openSecurity').addEventListener('click', async () => {
    clearSensitive(); message('securityMessage', '');
    try { await refreshSecurity(); dialog.showModal(); }
    catch (error) { message('accountError', error.message); }
  });
  async function submit(form, operation) {
    const buttons = [...form.querySelectorAll('button')]; buttons.forEach(b => { b.disabled = true; });
    message('securityMessage', '');
    try { await operation(); }
    catch (error) { message('securityMessage', error.message); }
    finally { buttons.forEach(b => { b.disabled = false; }); }
  }
  byId('setupForm').addEventListener('submit', event => {
    event.preventDefault(); const form = event.currentTarget;
    submit(form, async () => {
      const data = await request('2fa-start', { password: byId('setupPassword').value });
      form.reset();
      byId('totpQr').src = 'data:image/svg+xml;base64,' + btoa(data.qr_svg);
      message('totpKey', data.secret);
      byId('enrollment').hidden = false;
      byId('enableCode').focus();
    });
  });
  byId('copyTotpKey').addEventListener('click', async () => {
    try { await navigator.clipboard.writeText(byId('totpKey').textContent); message('securityMessage', 'Setup key copied.'); }
    catch (_) { message('securityMessage', 'Select the setup key and copy it manually.'); }
  });
  function showCodes(codes) {
    recovery = codes;
    message('recoveryList', codes.join('\n'));
    byId('recoveryPanel').hidden = false;
    byId('recoveryPanel').scrollIntoView({ block: 'nearest' });
  }
  byId('enableForm').addEventListener('submit', event => {
    event.preventDefault(); const form = event.currentTarget;
    submit(form, async () => {
      const data = await request('2fa-enable', { code: byId('enableCode').value.trim() });
      clearSensitive(); await refreshSecurity(); showCodes(data.recovery_codes);
      message('securityMessage', 'Two-factor authentication enabled. Save your recovery codes now. Other sessions have been signed out.');
    });
  });
  byId('factorActions').addEventListener('submit', event => {
    event.preventDefault(); const form = event.currentTarget, action = event.submitter.value;
    if (action === '2fa-disable' && !confirm('Turn off authenticator protection for this account?')) return;
    submit(form, async () => {
      const data = await request(action, { password: byId('factorPassword').value, code: byId('factorCode').value.trim() });
      clearSensitive(); await refreshSecurity();
      if (data.recovery_codes) showCodes(data.recovery_codes);
      message('securityMessage', action === '2fa-disable' ? 'Two-factor authentication disabled. Other sessions have been signed out.' : 'New recovery codes created. Previous codes no longer work.');
    });
  });
  byId('passwordForm').addEventListener('submit', event => {
    event.preventDefault(); const form = event.currentTarget;
    if (byId('newPassword').value !== byId('confirmPassword').value) { message('securityMessage', 'The new passwords do not match.'); return; }
    submit(form, async () => {
      await request('password', { password: byId('currentPassword').value, new_password: byId('newPassword').value, code: byId('passwordCode').value.trim() });
      clearSensitive(); await refreshSecurity(); message('securityMessage', 'Password changed. Other sessions have been signed out.');
    });
  });
  byId('sessionsForm').addEventListener('submit', event => {
    event.preventDefault(); const form = event.currentTarget;
    submit(form, async () => {
      await request('sessions-revoke', { password: byId('sessionPassword').value, code: byId('sessionCode').value.trim() });
      form.reset(); await refreshSecurity(); message('securityMessage', 'All other sessions have been signed out.');
    });
  });
  byId('downloadRecovery').addEventListener('click', () => {
    const blob = new Blob([`Email Checker recovery codes for ${user.username}\nEach code works once. Keep this file somewhere private.\n\n${recovery.join('\n')}\n`], { type: 'text/plain' });
    const url = URL.createObjectURL(blob), link = document.createElement('a');
    link.href = url; link.download = 'email-checker-recovery-codes.txt'; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  });
  byId('savedRecovery').addEventListener('click', () => { recovery = []; message('recoveryList', ''); byId('recoveryPanel').hidden = true; });
  (async () => {
    try {
      const status = await request('status');
      if (!status.enabled) { gate.hidden = true; app.hidden = false; resolveReady(null); return; }
      try { signedIn(await request('me')); }
      catch (error) { if (error.status !== 401) throw error; gate.hidden = false; loginView(); }
    } catch (_) { gate.hidden = false; byId('authForm').hidden = true; message('authError', 'Could not load account services. Refresh to try again.'); }
  })();
})();
